model:
  outputPath: ".output"
  tables:
    - name: "payment_method"
      count: "100"
      files: "1"
      columns:
        - name: "payment_type"
          expression: "randomString(15)"
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "created_time"
          expression: "randomDateTime()"
        - name: "account_number"
          expression: "randomString(16)"
        - name: "balance"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "currency"
          expression: "randomString(3)"
        - name: "name"
          expression: "randomString(255)"
        - name: "card_type"
          expression: "randomString(15)"
        - name: "exp_month"
          expression: "randomInt()"
        - name: "exp_year"
          expression: "randomInt()"
        - name: "number"
          expression: "randomString(255)"
        - name: "retailer"
          expression: "randomString(255)"
        - name: "voucher_code"
          expression: "randomString(25)"
    - name: "customer"
      count: "100"
      files: "1"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "address1"
          expression: "randomString(255)"
        - name: "address2"
          expression: "randomString(255)"
        - name: "city"
          expression: "randomString(255)"
        - name: "country_code"
          expression: "randomString(16)"
        - name: "country_name"
          expression: "randomString(36)"
        - name: "postcode"
          expression: "randomString(16)"
        - name: "created_time"
          expression: "randomDateTime()"
        - name: "email"
          expression: "randomString(128)"
        - name: "first_name"
          expression: "randomString(128)"
        - name: "last_name"
          expression: "randomString(128)"
        - name: "password"
          expression: "randomString(128)"
        - name: "telephone"
          expression: "randomString(128)"
        - name: "user_name"
          expression: "randomString(15)"
        - name: "payment_method_id"
          ref:
            name: "payment_method"
            column: "id"
    - name: "customer_payment_method"
      files: "1"
      columns:
        - name: "user_id"
          each:
            name: "customer"
            column: "id"
            multiplier: 1
        - name: "payment_method_id"
          each:
            name: "payment_method"
            column: "id"
            multiplier: 1
    - name: "attachment"
      count: "100"
      files: "1"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "binary_file"
          expression: "toBase64(randomBytes(512))"
        - name: "checksum"
          expression: "randomLong()"
        - name: "content_type"
          expression: "randomString(15)"
        - name: "created_time"
          expression: "randomDateTime()"
        - name: "description"
          expression: "randomString(256)"
        - name: "name"
          expression: "randomString(64)"
        - name: "size"
          expression: "randomLong()"
    - name: "orders"
      files: "1"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "bill_address1"
          expression: "randomString(255)"
        - name: "bill_address2"
          expression: "randomString(255)"
        - name: "bill_city"
          expression: "randomString(255)"
        - name: "bill_country_code"
          expression: "randomString(16)"
        - name: "bill_country_name"
          expression: "randomString(16)"
        - name: "bill_postcode"
          expression: "randomString(16)"
        - name: "bill_to_first_name"
          expression: "randomString(255)"
        - name: "bill_to_last_name"
          expression: "randomString(255)"
        - name: "date_placed"
          expression: "randomDateTime()"
        - name: "deliv_to_first_name"
          expression: "randomString(255)"
        - name: "deliv_to_last_name"
          expression: "randomString(255)"
        - name: "deliv_address1"
          expression: "randomString(255)"
        - name: "deliv_address2"
          expression: "randomString(255)"
        - name: "deliv_city"
          expression: "randomString(255)"
        - name: "deliv_country_code"
          expression: "randomString(16)"
        - name: "deliv_country_name"
          expression: "randomString(16)"
        - name: "deliv_postcode"
          expression: "randomString(16)"
        - name: "status"
          expression: "randomString(64)"
        - name: "amount"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "currency"
          expression: "randomString(255)"
        - name: "version"
          expression: "randomInt()"
        - name: "customer_id"
          each:
            name: "customer"
            column: "id"
            multiplier: 1
        - name: "payment_method_id"
          ref:
            name: "payment_method"
            column: "id"
    - name: "product"
      count: "100"
      files: "1"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "created_by"
          expression: "randomString(24)"
        - name: "created_time"
          expression: "randomDateTime()"
        - name: "last_modified_by"
          expression: "randomString(24)"
        - name: "last_modified_time"
          expression: "randomDateTime()"
        - name: "attributes"
          expression: "randomJson(1,1)"
        - name: "description"
          expression: "randomString(512)"
        - name: "name"
          expression: "randomString(128)"
        - name: "sku_code"
          expression: "randomString(128)"
        - name: "version"
          expression: "randomInt()"
    - name: "product_variation"
#      count: "100"
      files: "1"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "amount"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "currency"
          expression: "randomString(255)"
        - name: "sku_code"
          expression: "randomString(24)"
        - name: "version"
          expression: "randomInt()"
        - name: "product_id"
          each:
            name: "product"
            column: "id"
            multiplier: 1
    - name: "category"
      count: "100"
      files: "1"
      columns:
        - name: "category_type"
          expression: "randomString(15)"
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "created_time"
          expression: "randomDateTime()"
        - name: "description"
          expression: "randomString(255)"
        - name: "left_node"
          expression: "randomLong()"
        - name: "name"
          expression: "randomString(64)"
        - name: "right_node"
          expression: "randomLong()"
        - name: "version"
          expression: "randomInt()"
        - name: "parent_id"
          expression: "randomLong()"
    - name: "categorized_product"
      files: "1"
      columns:
        - name: "category_id"
          each:
            name: "category"
            column: "id"
            multiplier: 1
        - name: "created_time"
          expression: "randomDateTime()"
        - name: "expires"
          expression: "randomDateTime()"
        - name: "product_id"
          each:
            name: "product"
            column: "id"
            multiplier: 1
        - name: "username"
          expression: "randomString(16)"
        - name: "rowid"
          gen:
            type: "sequence"
            from: "1"
            step: 1
    - name: "product_variation_attribute"
#      count: "100"
      files: "1"
      columns:
        - name: "product_variation_id"
          each:
            name: "product_variation"
            column: "id"
            multiplier: 1
        - name: "value"
          expression: "randomString(512)"
        - name: "name"
          expression: "randomString(55)"
    - name: "product_attachment"
      files: "1"
      columns:
        - name: "product_id"
          each:
            name: "product"
            column: "id"
            multiplier: 1
        - name: "attachment_id"
          each:
            name: "attachment"
            column: "id"
            multiplier: 1
        - name: "rowid"
          gen:
            type: "sequence"
            from: "1"
            step: 1
    - name: "order_item"
      files: "1"
      columns:
        - name: "order_id"
          each:
            name: "orders"
            column: "id"
            multiplier: 1
        - name: "load_type"
          expression: "randomString(16)"
        - name: "product_variation_id"
          each:
            name: "product_variation"
            column: "id"
            multiplier: 1
        - name: "quantity"
          expression: "randomInt()"
        - name: "status"
          expression: "randomString(64)"
        - name: "amount"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "currency"
          expression: "randomString(255)"
        - name: "weight_kg"
          expression: "randomDouble()"
        - name: "item_pos"
          gen:
            type: "unordered"
            batchSize: 512
    - name: "product_tag"
      files: "1"
      columns:
        - name: "product_id"
          each:
            name: "product"
            column: "id"
            multiplier: 1
        - name: "name"
          expression: "randomString(64)"
        - name: "rowid"
          gen:
            type: "sequence"
            from: "1"
            step: 1
  import:
    options:
      delimiter: ","
      skip: "1"
      allow_quoted_null: "null"
      fields_enclosed_by: '"'
    file: "import.sql"
    prefix: "http://${local-ip}:8090/"
